### ISSUE TITLE
Crawlovatelná data Moravskoslezského kraje a dalších

### ISSUE THREAD

**Issue by h0n24** [lynt-smitka/khs-crawler#1]
**Dobrá zpráva!**

### TLDR

Našel jsem Google Document, který by se dal použít pro doplnění dat, která jsou obtížná k sehnání (tj. Moravskoslezský kraj).

> https://docs.google.com/spreadsheets/d/1BQJH9l4e3oUvCMsItnOx0UPa6EVjbLl24C9_lBfu908/edit#gid=0

### Postup zvoleného reverzního inženýrství

1.  Všiml jsem si, že Deník.cz používá veřejné tableau.com tabulky, například na této stránce: https://www.denik.cz/z_domova/koronavirus-mapa.html

2. Odkazy vedou na public.tableau profil den.k.data, například ukázka pro Moravskoslezský kraj: https://public.tableau.com/profile/den.k.data#!/vizhome/2603-koronavirus-okresy/dshbrdkrajMSK

3. Z kódu je vidět, že data se berou z https://public.tableau.com/workbooks/2603-koronavirus-okresy.twb (veřejně crawlovatelné/ stáhnutelné, soubor s příponou `.twb`)

4. Při inspekci kódu se data dost opakují, což vedlo k tezi, že data můžou být zabalená.

5. Je možné soubor rozbalit jako `.zip`.

6. Otevřít složku. Otevřít první soubor `.twb` ve složce (složky Data a Image nejsou třeba), kde například soubor se jmenuje: 2503-koronavirus-CZ-okresy5.twb (pozor, název není stejný jako stahovaný)

7. Tento soubor `.twb` (stejná přípona, ale jiné chování) se dá parsovat jako `xml` soubor

8. Dá se přes xml DOM přečíst `<workbook> <datascources>`

9. Při chvíli hledání se dají najít zdrojová data, která jsou ve formátu tabulky.

10. Tabulka se bere z Google Sheets, pak už stačí jen najít `<named-connection>` element a atribut `googleSheetId`

11. Většina tabulek vede na https://docs.google.com/spreadsheets/d/1BQJH9l4e3oUvCMsItnOx0UPa6EVjbLl24C9_lBfu908/edit#gid=0

Předpokládám, že adresa se nebude příliš měnit. U jednotlivých sekcí jsou data aktualizace, dá se s tím pracovat při porovnávání. Předpokládám, že počet nakažených se nebude snižovat, protože se jedná (nejspíš) o celkové nakažené, čili stačí klasické porovnání číselných dat ve smyslu menší větší.

Snad pomůže.

Mám ten postup vypsat na https://www.sablatura.info/covid/hygienicke-stanice/ a nasdílet dále, nebo stačí jen nechat tady v issues?

S pozdravem
Jan Šablatura

**Comment by h0n24** [comment]
Update: Veronika Jílková a další to dělají každý den ručně, tak je ale otázka, jak moc jsou data stabilní.

Více viz: https://www.facebook.com/groups/covid19cz/permalink/1444070019096456/?comment_id=1444180482418743&reply_comment_id=1444193945750730

**Comment by helb** [comment]
[Zkousim cist cisla z grafu](https://github.com/lynt-smitka/khs-crawler/pull/2) na khsova.cz a funguje to zatim pekne.

Jen bych to potreboval vyzkouset s nejakym jinym grafem, nez tim patecnim, co maji jako posledni na webu. Nemate nahodou prosim nekde neco starsiho ulozeneho?

**Comment by h0n24** [comment]
@helb 

### Soubory z Google cache

Přímo obrázek z 24. 3.: http://www.khsova.cz/images/koronavirus_statistika_celkem_na_100tis-20200325.png

Odkaz na cache: http://webcache.googleusercontent.com/search?q=cache:GPr0W6sPOHYJ:www.khsova.cz/homepage/korona-statistika+&cd=1&hl=cs&ct=clnk&gl=cz

Myslím, že právě 24. 3. začali. Určitě se to tam neobjevovalo každý den.

### Vygenerování vlastních
Každopádně, protože to vypadá, že používají highchart.js grafy (odhaduji obecně podle zkušeností a  zaokrouhlení rohů jednotlivých barů), myslím, že by stačilo si nějaké vygenerovat na: https://www.highcharts.com/demo/bar-basic

#### Postup, jakým to (dle mého) dělají:
1. Vygenerují graf/vytvoří graf
2. V roletkovém menu vpravo nahoře kliknou na download png image

### Zkoušel jsem a nepomohlo
- hledat přes web archive: https://web.archive.org/web/20200601000000*/http://www.khsova.cz/

### Potenciální problém
Z nějakého důvodu je dnes na hlavní stránce http://www.khsova.cz/ **aktuálnější obrázek**: http://www.khsova.cz/sliders/slider_mapa_koronavirus-0330b.jpg **než na podstránce**: http://www.khsova.cz/homepage/korona-statistika

Možná by bylo vhodné data porovnávat i s tímto.

**Comment by helb** [comment]
Diky!

Google a webarchive jsem zkousel, ale v tom grafu na obrazku bohuzel vubec nejsou ta cisla. Tak snad zustanou pro priste u toho soucasneho formatu…

Mapa je skoro necitelna i pro me, tam bych na OCR moc nespolehal, ale zkusim to…

Generovani vlastnich highcharts by asi mohlo pomoci, diky za napad. Mne to prislo na prvni pohled jako grafy z Google sheets:


![chickadee_20200330_234918](https://user-images.githubusercontent.com/178133/77965364-5a2ec500-72d0-11ea-9ccb-de0f6af8dad7.png)

**Comment by lynt-smitka** [comment]
@helb  Mergnul jsem PR, vyzkouším jak to bude fungovat v praxi. Jen jakou používáš verzi Tesseractu? Já mám ještě řadu 3 a tam jsem měl problém takto malá čísla přečíst. Update na 4 by ale neměl být problém.

**Comment by helb** [comment]
@lynt-smitka mam 4.1.1, zkusim to s trojkou

**Comment by helb** [comment]
S trojkou to moc neslo, ale po zvetseni obrazku uz jde. :) Podrobnosti v PR.

**Comment by kalab-oto** [comment]
Na stránkách kraje (https://koronavirus.msk.cz/) je tabulka pro ORP, což se dá posčítat a udělat z toho okresy. Čísla odpovídají datům z KHS - viz mapy KHS, které na twitteru pravidelně publikuje hejtman (30.3. např. https://twitter.com/ivondrak/status/1244722258192609293)

**Comment by helb** [comment]
@kalab-oto Diky, to vypada slibne. Parser tu: https://github.com/lynt-smitka/khs-crawler/pull/3

**Comment by h0n24** [comment]
Uzavírám, funkční parser pro Moravskoslezský kraj již máme. ✔️

Chybí jen dořešit stabilitu Středočeského kraje, více viz: #4
