### ISSUE TITLE
Středočeský kraj - změny

### ISSUE THREAD

**Issue by lynt-smitka** [lynt-smitka/khs-crawler#4]
Středočeský kraj publikuje nekonzistentně... Jeden den je to ve formě obrázku, další den je textový výpis a pak opět obrázek. U obrázku se navíc mění pozice textů (viz Kladno)...

http://www.khsstc.cz/Admin/_upload/images/1/COVID%2031_3.jpg
http://www.khsstc.cz/Admin/_upload/images/1/COVID%2027_3.jpg

**Comment by h0n24** [comment]
Obrázek je totiž výstup z národního systému ISIN (dříve EPIDAT).

Pracovníci hygieny středočeského kraje to asi vypisují ručně, tzn nejspíš MUDr. Lilian Rumlová a Bc. Andrea Bobková. A tipuji z ISIN stahují jenom ten obrázek.

### Více info o ISIN
- http://www.szu.cz/publikace/data/infekce-v-cr
- https://www.ipvz.cz/vzdelavaci-akce/51464-kurz-instruktaz-k-epidemiologickemu-systemu-isin
- http://www.szu.cz/publikace/data/2020

Ale co s tím, netuším :( Třeba něco napadne @helb nebo @kalab-oto

**Comment by kalab-oto** [comment]
Je tam další změna, začali používat [ArcGIS mapu](http://www.khsstc.cz/dokumenty/aktualni-situace-ve-vyskytu-koronaviru-ve-stredoceskem-kraji-5723_5723_161_1.html). Ta data v mapě se načítají z [ArcGIS REST služby](https://services7.arcgis.com/6U6Ps5FLizN0Qujz/ArcGIS/rest/services/Počet_onemocnění_COVID19_ve_Středočeském_kraji/FeatureServer/0), která se dá dotazovat :)

např. pro Mělník (atributy PocetPripadu,PocetVylecenych,PocetZemrelych):

https://services7.arcgis.com/6U6Ps5FLizN0Qujz/ArcGIS/rest/services/Počet_onemocnění_COVID19_ve_Středočeském_kraji/FeatureServer/0/query?where=nazev='Mělník'&outFields=PocetPripadu%2CPocetVylecenych%2CPocetZemrelych&returnGeometry=false&f=pjson&token=

**Comment by h0n24** [comment]
Naštěstí ArcGIS REST Service trpí na SQL injection bug (where 1=1).

### Všechna města a všechny užitečné atributy:
https://services7.arcgis.com/6U6Ps5FLizN0Qujz/ArcGIS/rest/services/Po%C4%8Det_onemocn%C4%9Bn%C3%AD_COVID19_ve_St%C5%99edo%C4%8Desk%C3%A9m_kraji/FeatureServer/0/query?where=1%3D1&geometryType=esriGeometryEnvelope&geometryPrecision=6&spatialRel=esriSpatialRelIntersects&outFields=kod%2Cnazev%2CPocetPripadu%2CPocetVylecenych%2CPocetZemrelych%2CPocetObyvatel&resultOffset=0&returnGeometry=false&returnZ=false&returnM=false&returnIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&returnTrueCurves=false&returnExtentsOnly=false&f=json

#### Může se hodit:
`outFields=*` vypíše všechny atributy
`f=json` je minimalizovaný kód, kdežto `f=pjson` je prettified (odsazení, tabulátory apod.)

**Comment by helb** [comment]
Napsal jsem parser pro to ArcGIS API a mapa mezitim z webu hygieny zas zmizela. :D

Ted tam je jen jednoducha tabulka, ta se bude stahovat pekne, ale doufam ze jim vydrzi aspon do zitra…

Update 4.4. 00:30 – zmizela tabulka, mapa je v trochu jine podobe zpet :man_shrugging:

**Comment by helb** [comment]
Parser tady: #13. Ale trochu se bojim, ze zitra prijdou do prace a zas tam daji misto mapy neco jineho :)

Update 6.4. 21:40 – ted tam pro jistotu neni vubec nic, achjo… Ale mapa samotna je asi aktualizovana, odkazuje na ni i krajsky web.

![chickadee_20200406_213629](https://user-images.githubusercontent.com/178133/78598080-27d81700-783e-11ea-8f7f-32bc0ad0a264.png)

**Comment by h0n24** [comment]
@lynt-smitka prosím, schvalte ty pull-requesty, co se nahromadily (aktuálně celkem 6), ať se to může sypat přímo do zdrojové tabulky. 

Případně dejte někomu možnost je schvalovat (@helb např.). Myslím, že je zbytečné dělat další fork, ať všechno zůstane na jednom místě.

**Comment by helb** [comment]
Dostal jsem pristup, dekuju.

Tohle muzeme asi zavrit, jen v tabulce v Readme jeste zmenim zdroj z obrazku na ten ArcGIS.
